const List<({String code, String flag, String name})> languageOptions = [
  (code: 'en', flag: '🇬🇧', name: 'English'),
  (code: 'cs', flag: '🇨🇿', name: 'Čeština'),
  (code: 'de', flag: '🇩🇪', name: 'Deutsch'),
  (code: 'fr', flag: '🇫🇷', name: 'Français'),
  (code: 'it', flag: '🇮🇹', name: 'Italiano'),
  (code: 'es', flag: '🇪🇸', name: 'Español'),
];

const Map<String, Map<String, String>> uiStrings = {
  'continue': {
    'en': 'Continue',
    'cs': 'Pokračovat',
    'de': 'Fortsetzen',
    'fr': 'Continuer',
    'it': 'Continua',
    'es': 'Continuar',
  },
  'newGame': {
    'en': 'New Game',
    'cs': 'Nová hra',
    'de': 'Neues Spiel',
    'fr': 'Nouvelle partie',
    'it': 'Nuova partita',
    'es': 'Nueva partida',
  },
  'language': {
    'en': 'Language',
    'cs': 'Jazyk',
    'de': 'Sprache',
    'fr': 'Langue',
    'it': 'Lingua',
    'es': 'Idioma',
  },
  'settings': {
    'en': 'Settings',
    'cs': 'Nastavení',
    'de': 'Einstellungen',
    'fr': 'Paramètres',
    'it': 'Impostazioni',
    'es': 'Ajustes',
  },
  'exitGame': {
    'en': 'Exit Game',
    'cs': 'Ukončit hru',
    'de': 'Spiel beenden',
    'fr': 'Quitter le jeu',
    'it': 'Esci dal gioco',
    'es': 'Salir del juego',
  },
  'back': {
    'en': 'Back',
    'cs': 'Zpět',
    'de': 'Zurück',
    'fr': 'Retour',
    'it': 'Indietro',
    'es': 'Atrás',
  },
  'artFocus': {
    'en': 'Art Focus',
    'cs': 'Obraz',
    'de': 'Kunstmodus',
    'fr': 'Mode art',
    'it': 'Modalità arte',
    'es': 'Modo arte',
  },
  'storyFocus': {
    'en': 'Story Focus',
    'cs': 'Příběh',
    'de': 'Geschichtenmodus',
    'fr': 'Mode histoire',
    'it': 'Modalità storia',
    'es': 'Modo historia',
  },
  'endOfStory': {
    'en': 'You have reached the end of the story.\n\nThank you for playing!\n\nYou can start the story again and choose different paths.',
    'cs': 'Dosáhli jste konce příběhu.\n\nDěkujeme za hraní!\n\nMůžete příběh začít znovu a zvolit si jiné cesty.',
    'de': 'Sie haben das Ende der Geschichte erreicht.\n\nVielen Dank fürs Spielen!\n\nSie können die Geschichte erneut beginnen und andere Wege wählen.',
    'fr': 'Vous avez atteint la fin de l\'histoire.\n\nMerci d\'avoir joué !\n\nVous pouvez recommencer l\'histoire et choisir des chemins différents.',
    'it': 'Hai raggiunto la fine della storia.\n\nGrazie per aver giocato!\n\nPuoi ricominciare la storia e scegliere percorsi diversi.',
    'es': 'Has llegado al final de la historia.\n\n¡Gracias por jugar!\n\nPuedes empezar la historia de nuevo y elegir caminos diferentes.',
  },
  'about': {
    'en': 'About',
    'cs': 'O aplikaci',
    'de': 'Über',
    'fr': 'À propos',
    'it': 'Informazioni',
    'es': 'Acerca de',
  },
  'aboutDescription': {
    'en': 'An interactive visual novel set in the heart of Tuscany.\n\nFollow Elara on her healing journey through the Golden Valley.',
    'cs': 'Interaktivní vizuální novela zasazená do srdce Toskánska.\n\nSledujte Elaru na její léčivé cestě skrze Zlaté údolí.',
    'de': 'Ein interaktiver visueller Roman im Herzen der Toskana.\n\nBegleiten Sie Elara auf ihrer heilenden Reise durch das Goldene Tal.',
    'fr': 'Un roman visuel interactif au coeur de la Toscane.\n\nSuivez Elara dans son voyage de guérison à travers la Vallée dorée.',
    'it': 'Un romanzo visivo interattivo nel cuore della Toscana.\n\nSegui Elara nel suo viaggio di guarigione attraverso la Valle dorata.',
    'es': 'Una novela visual interactiva en el corazón de la Toscana.\n\nSigue a Elara en su viaje de sanación a través del Valle dorado.',
  },
  'aboutFeedback': {
    'en': 'Feedback',
    'cs': 'Zpětná vazba',
    'de': 'Feedback',
    'fr': 'Commentaires',
    'it': 'Feedback',
    'es': 'Comentarios',
  },
  'returnToMenu': {
    'en': 'Return to Main Menu',
    'cs': 'Zpět do hlavního menu',
    'de': 'Zurück zum Hauptmenü',
    'fr': 'Retour au menu principal',
    'it': 'Torna al menu principale',
    'es': 'Volver al menú principal',
  },
};

String ui(String key, String lang) => uiStrings[key]?[lang] ?? uiStrings[key]?['en'] ?? key;
